name: I.R.I.S Utilities CI

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2
      - name: Configure files
        run: mv .env.example .env
      - name: Setup Node.js v14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: prettier -c .
